# Generated by Django 5.1 on 2024-08-10 17:44

import scraperapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('vse', 'Vse'), ('teorija', 'Teorija'), ('voznja', 'Voznja')], default='vse', max_length=15)),
                ('current_date', models.DateField(validators=[scraperapi.validators.validate_event_date])),
            ],
        ),
    ]
